---
# Configuration par défaut pour ImproveDoc
# Ce fichier définit les paramètres généraux et les valeurs par défaut

# Configuration LLM
llm:
  temperature: 0.7
  max_tokens: 16384  # Augmenté pour permettre des enrichissements plus complets
  base_url: "https://openrouter.ai/api/v1"
  default_model: "openrouter/openrouter/anthropic/claude-sonnet-4"

# Configuration Wikipedia
wikipedia:
  language: "fr"
  max_search_results: 5
  default_summary_sentences: 3

# Configuration de la mémoire
memory:
  storage_dir: "./improvedoc_memory"
  embedder: "intfloat/multilingual-e5-large"
  
# Configuration du processus d'amélioration
enhance:
  max_sections: 50  # Augmenté pour traiter des documents plus longs sans troncature
  preserve_structure: true  # Garantit que la structure originale est respectée
  add_links: true  # Active l'ajout de liens Wikipédia
  verify_facts: true  # Active la vérification factuelle